/* ============================================================
   YAPON TILI — data.js
   JLPT N4 Kanji (300) + Katakana Chart + Katakana Words
   ============================================================ */

'use strict';

const KANJI_RAW = [
  {k:'悪',m:"Yomon",on:'アク・オ',kun:'わる(い)',ex:'悪人',em:"Yomon odam"},
  {k:'安',m:"Arzon; xotirjam",on:'アン',kun:'やす(い)',ex:'安心',em:"Xotirjamlik"},
  {k:'暗',m:"Qorong'i",on:'アン',kun:'くら(い)',ex:'暗い',em:"Qorong'i"},
  {k:'以',m:"...dan beri; bilan",on:'イ',kun:'もっ(て)',ex:'以上',em:"Bundan ko'proq"},
  {k:'医',m:"Tibbiyot",on:'イ',kun:'い',ex:'医者',em:"Shifokor"},
  {k:'意',m:"Ma'no; niyat",on:'イ',kun:'こころ',ex:'意味',em:"Ma'no"},
  {k:'引',m:"Tortmoq",on:'イン',kun:'ひ(く)',ex:'引く',em:"Tortmoq"},
  {k:'飲',m:"Ichmoq",on:'イン',kun:'の(む)',ex:'飲み物',em:"Ichimlik"},
  {k:'運',m:"Omad; tashish",on:'ウン',kun:'はこ(ぶ)',ex:'運動',em:"Jismoniy mashq"},
  {k:'映',m:"Aks ettirmoq",on:'エイ',kun:'うつ(る)',ex:'映画',em:"Kino"},
  {k:'駅',m:"Stansiya; bekat",on:'エキ',kun:'—',ex:'駅',em:"Poyezd stansiyasi"},
  {k:'遠',m:"Uzoq",on:'エン・オン',kun:'とお(い)',ex:'遠い',em:"Uzoq"},
  {k:'押',m:"Bosmoq; itarmoq",on:'オウ',kun:'お(す)',ex:'押す',em:"Bosmoq"},
  {k:'屋',m:"Do'kon; uy",on:'オク',kun:'や',ex:'本屋',em:"Kitob do'koni"},
  {k:'音',m:"Tovush; ovoz",on:'オン・イン',kun:'おと・ね',ex:'音楽',em:"Musiqa"},
  {k:'化',m:"O'zgartirmoq",on:'カ・ケ',kun:'ば(ける)',ex:'文化',em:"Madaniyat"},
  {k:'歌',m:"Qo'shiq",on:'カ',kun:'うた(う)',ex:'歌手',em:"Qo'shiqchi"},
  {k:'家',m:"Uy; oila",on:'カ・ケ',kun:'いえ・や',ex:'家族',em:"Oila"},
  {k:'画',m:"Rasm; surat",on:'ガ・カク',kun:'かく',ex:'映画',em:"Kino"},
  {k:'会',m:"Uchrashuv; jamiyat",on:'カイ・エ',kun:'あ(う)',ex:'会社',em:"Kompaniya"},
  {k:'海',m:"Dengiz",on:'カイ',kun:'うみ',ex:'海外',em:"Xorijda"},
  {k:'回',m:"Qaytish; marta",on:'カイ・エ',kun:'まわ(る)',ex:'回る',em:"Aylanmoq"},
  {k:'買',m:"Sotib olmoq",on:'バイ',kun:'か(う)',ex:'買い物',em:"Xarid qilish"},
  {k:'角',m:"Burchak; shox",on:'カク',kun:'かど・つの',ex:'角',em:"Burchak"},
  {k:'楽',m:"Quvnoq; musiqa",on:'ガク・ラク',kun:'たの(しい)',ex:'音楽',em:"Musiqa"},
  {k:'漢',m:"Xitoy",on:'カン',kun:'おとこ',ex:'漢字',em:"Xitoy yozuvi"},
  {k:'起',m:"Turmoq; boshlamoq",on:'キ',kun:'お(きる)',ex:'起きる',em:"Turmoq (uyg'onmoq)"},
  {k:'気',m:"Ruh; havo; his",on:'キ・ケ',kun:'き',ex:'天気',em:"Ob-havo"},
  {k:'記',m:"Yozib qolmoq",on:'キ',kun:'しる(す)',ex:'日記',em:"Kun tarixi"},
  {k:'急',m:"Shoshmoq; tezkor",on:'キュウ',kun:'いそ(ぐ)',ex:'急ぐ',em:"Shoshmoq"},
  {k:'教',m:"O'qitmoq; o'rgatmoq",on:'キョウ',kun:'おし(える)',ex:'教室',em:"Sinf xonasi"},
  {k:'強',m:"Kuchli; qattiq",on:'キョウ',kun:'つよ(い)',ex:'強い',em:"Kuchli"},
  {k:'近',m:"Yaqin",on:'キン',kun:'ちか(い)',ex:'近く',em:"Yaqin atrofda"},
  {k:'空',m:"Osmon; bo'sh",on:'クウ',kun:'そら・から',ex:'空港',em:"Aeroport"},
  {k:'薬',m:"Dori",on:'ヤク',kun:'くすり',ex:'薬局',em:"Dorixona"},
  {k:'軽',m:"Yengil",on:'ケイ',kun:'かる(い)',ex:'軽い',em:"Yengil"},
  {k:'元',m:"Asl; sog'lom",on:'ゲン・ガン',kun:'もと',ex:'元気',em:"Sog'lom; baquvvat"},
  {k:'言',m:"Aytmoq; so'z",on:'ゲン・ゴン',kun:'い(う)',ex:'言葉',em:"So'z; til"},
  {k:'古',m:"Eski",on:'コ',kun:'ふる(い)',ex:'古い',em:"Eski"},
  {k:'語',m:"Til; so'z",on:'ゴ',kun:'かた(る)',ex:'日本語',em:"Yapon tili"},
  {k:'好',m:"Yaxshi ko'rmoq",on:'コウ',kun:'す(き)',ex:'好き',em:"Yoqtirmoq"},
  {k:'工',m:"Ish; qurilish",on:'コウ・ク',kun:'—',ex:'工場',em:"Zavod"},
  {k:'校',m:"Maktab",on:'コウ',kun:'—',ex:'学校',em:"Maktab"},
  {k:'考',m:"O'ylamoq",on:'コウ',kun:'かんが(える)',ex:'考える',em:"O'ylamoq"},
  {k:'行',m:"Bormoq; qator",on:'コウ・ギョウ・アン',kun:'い(く)',ex:'旅行',em:"Sayohat"},
  {k:'高',m:"Baland; qimmat",on:'コウ',kun:'たか(い)',ex:'高い',em:"Qimmat; baland"},
  {k:'合',m:"Mos kelmoq; birlashtirmoq",on:'ゴウ・ガッ',kun:'あ(う)',ex:'合う',em:"Mos kelmoq"},
  {k:'国',m:"Mamlakat; davlat",on:'コク',kun:'くに',ex:'外国',em:"Xorijiy mamlakat"},
  {k:'今',m:"Hozir; bugun",on:'コン・キン',kun:'いま',ex:'今日',em:"Bugun"},
  {k:'左',m:"Chap",on:'サ',kun:'ひだり',ex:'左手',em:"Chap qo'l"},
  {k:'作',m:"Yaratmoq; qilmoq",on:'サク・サ',kun:'つく(る)',ex:'作る',em:"Yaratmoq"},
  {k:'山',m:"Tog'",on:'サン',kun:'やま',ex:'富士山',em:"Fuji tog'i"},
  {k:'使',m:"Ishlatmoq; xizmatchi",on:'シ',kun:'つか(う)',ex:'使う',em:"Ishlatmoq"},
  {k:'始',m:"Boshlash",on:'シ',kun:'はじ(める)',ex:'始める',em:"Boshlash"},
  {k:'次',m:"Keyingi",on:'ジ・シ',kun:'つぎ',ex:'次の',em:"Keyingi"},
  {k:'字',m:"Harf; belgi",on:'ジ',kun:'—',ex:'漢字',em:"Kanji belgi"},
  {k:'時',m:"Vaqt; soat",on:'ジ',kun:'とき',ex:'時間',em:"Vaqt"},
  {k:'自',m:"O'z; o'zi",on:'ジ・シ',kun:'みずか(ら)',ex:'自分',em:"O'zi"},
  {k:'写',m:"Nusxa ko'chirmoq; suratga olmoq",on:'シャ',kun:'うつ(す)',ex:'写真',em:"Surat"},
  {k:'社',m:"Kompaniya; ibodatxona",on:'シャ',kun:'やしろ',ex:'会社',em:"Kompaniya"},
  {k:'週',m:"Hafta",on:'シュウ',kun:'—',ex:'今週',em:"Bu hafta"},
  {k:'書',m:"Yozmoq; kitob",on:'ショ',kun:'か(く)',ex:'図書館',em:"Kutubxona"},
  {k:'少',m:"Oz; bir oz",on:'ショウ',kun:'すく(ない)',ex:'少し',em:"Bir oz"},
  {k:'場',m:"Joy; maydon",on:'ジョウ',kun:'ば',ex:'場所',em:"Joy"},
  {k:'色',m:"Rang",on:'ショク・シキ',kun:'いろ',ex:'色',em:"Rang"},
  {k:'食',m:"Ovqat; yemoq",on:'ショク',kun:'た(べる)',ex:'食べ物',em:"Taom"},
  {k:'新',m:"Yangi",on:'シン',kun:'あたら(しい)',ex:'新聞',em:"Gazeta"},
  {k:'人',m:"Odam; shaxs",on:'ジン・ニン',kun:'ひと',ex:'外国人',em:"Chet el fuqarosi"},
  {k:'水',m:"Suv",on:'スイ',kun:'みず',ex:'水曜日',em:"Chorshanba"},
  {k:'正',m:"To'g'ri; adolatli",on:'セイ・ショウ',kun:'ただ(しい)',ex:'正しい',em:"To'g'ri"},
  {k:'声',m:"Ovoz (inson ovozi)",on:'セイ・ショウ',kun:'こえ',ex:'声',em:"Ovoz"},
  {k:'生',m:"Hayot; tirik",on:'セイ・ショウ',kun:'い(きる)',ex:'学生',em:"Talaba"},
  {k:'石',m:"Tosh",on:'セキ・シャク',kun:'いし',ex:'石',em:"Tosh"},
  {k:'切',m:"Kesmoq; muhim",on:'セツ・サイ',kun:'き(る)',ex:'大切',em:"Muhim; aziz"},
  {k:'線',m:"Chiziq; yo'l",on:'セン',kun:'—',ex:'電車線',em:"Temir yo'l"},
  {k:'前',m:"Oldin; ilgari",on:'ゼン',kun:'まえ',ex:'午前',em:"Ertalab"},
  {k:'走',m:"Yugurmoq",on:'ソウ',kun:'はし(る)',ex:'走る',em:"Yugurmoq"},
  {k:'多',m:"Ko'p",on:'タ',kun:'おお(い)',ex:'多い',em:"Ko'p"},
  {k:'体',m:"Tana; jismoniy",on:'タイ・テイ',kun:'からだ',ex:'体',em:"Tana"},
  {k:'台',m:"Stend; son sanash",on:'ダイ・タイ',kun:'—',ex:'台所',em:"Oshxona"},
  {k:'大',m:"Katta; ulkan",on:'ダイ・タイ',kun:'おお(きい)',ex:'大学',em:"Universitet"},
  {k:'短',m:"Qisqa",on:'タン',kun:'みじか(い)',ex:'短い',em:"Qisqa"},
  {k:'知',m:"Bilmoq",on:'チ',kun:'し(る)',ex:'知る',em:"Bilmoq"},
  {k:'茶',m:"Choy; jigarrang",on:'チャ・サ',kun:'—',ex:'お茶',em:"Choy"},
  {k:'地',m:"Yer; zamin",on:'チ・ジ',kun:'—',ex:'地図',em:"Xarita"},
  {k:'着',m:"Kiymoq; kelmoq",on:'チャク',kun:'き(る)',ex:'着く',em:"Etib kelmoq"},
  {k:'長',m:"Uzun; rahbar",on:'チョウ',kun:'なが(い)',ex:'身長',em:"Bo'y"},
  {k:'朝',m:"Ertalab",on:'チョウ',kun:'あさ',ex:'毎朝',em:"Har ertalab"},
  {k:'通',m:"O'tmoq; yo'l",on:'ツウ・ツ',kun:'とお(る)',ex:'通る',em:"O'tmoq"},
  {k:'低',m:"Past",on:'テイ',kun:'ひく(い)',ex:'低い',em:"Past"},
  {k:'点',m:"Nuqta; ball",on:'テン',kun:'—',ex:'点数',em:"Ball; natija"},
  {k:'店',m:"Do'kon",on:'テン',kun:'みせ',ex:'店',em:"Do'kon"},
  {k:'電',m:"Elektr",on:'デン',kun:'—',ex:'電話',em:"Telefon"},
  {k:'道',m:"Yo'l; usul",on:'ドウ',kun:'みち',ex:'道路',em:"Yo'l"},
  {k:'読',m:"O'qimoq",on:'ドク・トク',kun:'よ(む)',ex:'読書',em:"Kitob o'qish"},
  {k:'肉',m:"Go'sht",on:'ニク',kun:'—',ex:'牛肉',em:"Mol go'shti"},
  {k:'入',m:"Kirmoq; solmoq",on:'ニュウ',kun:'い(る)',ex:'入口',em:"Kirish"},
  {k:'年',m:"Yil",on:'ネン',kun:'とし',ex:'今年',em:"Bu yil"},
  {k:'白',m:"Oq",on:'ハク・ビャク',kun:'しろ',ex:'白い',em:"Oq"},
  {k:'半',m:"Yarim",on:'ハン',kun:'なか(ば)',ex:'半分',em:"Yarim"},
  {k:'飯',m:"Guruch; ovqat",on:'ハン',kun:'めし',ex:'ご飯',em:"Ovqat (guruch)"},
  {k:'父',m:"Ota",on:'フ',kun:'ちち',ex:'お父さん',em:"Ota"},
  {k:'母',m:"Ona",on:'ボ',kun:'はは',ex:'お母さん',em:"Ona"},
  {k:'不',m:"Emas; yo'q",on:'フ・ブ',kun:'—',ex:'不便',em:"Noqulay"},
  {k:'物',m:"Narsa; buyum",on:'ブツ・モツ',kun:'もの',ex:'食べ物',em:"Taom"},
  {k:'文',m:"Matn; harf",on:'ブン・モン',kun:'ふみ',ex:'文章',em:"Gap; yozma matn"},
  {k:'平',m:"Tekis; tinch",on:'ヘイ・ビョウ',kun:'たい(ら)',ex:'平和',em:"Tinchlik"},
  {k:'別',m:"Boshqa; ajratmoq",on:'ベツ',kun:'わか(れる)',ex:'別の',em:"Boshqa"},
  {k:'勉',m:"Tirishmoq",on:'ベン',kun:'—',ex:'勉強',em:"O'qish; tirishish"},
  {k:'方',m:"Yo'nalish; kishi",on:'ホウ',kun:'かた',ex:'方法',em:"Usul"},
  {k:'北',m:"Shimol",on:'ホク',kun:'きた',ex:'北海道',em:"Hokkaido"},
  {k:'本',m:"Kitob; asl",on:'ホン',kun:'もと',ex:'日本',em:"Yaponiya"},
  {k:'妹',m:"Kichik singil",on:'マイ',kun:'いもうと',ex:'妹',em:"Kichik singil"},
  {k:'問',m:"Savol; muammo",on:'モン',kun:'と(う)',ex:'問題',em:"Muammo; savol"},
  {k:'野',m:"Dala; burg'u",on:'ヤ',kun:'の',ex:'野菜',em:"Sabzavot"},
  {k:'有',m:"Bor; mavjud",on:'ユウ・ウ',kun:'あ(る)',ex:'有名',em:"Mashhur"},
  {k:'夜',m:"Kecha; tun",on:'ヤ',kun:'よる・よ',ex:'夜中',em:"Tun yarmi"},
  {k:'来',m:"Kelmoq",on:'ライ',kun:'く(る)',ex:'来月',em:"Kelasi oy"},
  {k:'理',m:"Sabab; mantiq",on:'リ',kun:'—',ex:'料理',em:"Taom pishirish"},
  {k:'立',m:"Turmoq; o'rnatmoq",on:'リツ・リュウ',kun:'た(つ)',ex:'立つ',em:"Turmoq"},
  {k:'旅',m:"Sayohat",on:'リョ',kun:'たび',ex:'旅行',em:"Sayohat"},
  {k:'料',m:"Narx; to'lov",on:'リョウ',kun:'—',ex:'料理',em:"Oshpazlik"},
  {k:'力',m:"Kuch",on:'リョク・リキ',kun:'ちから',ex:'力',em:"Kuch"},
  {k:'林',m:"O'rmon (kichik)",on:'リン',kun:'はやし',ex:'林',em:"O'rmon"},
  {k:'冷',m:"Sovuq; sovutmoq",on:'レイ',kun:'つめ(たい)',ex:'冷たい',em:"Sovuq (narsa)"},
  {k:'話',m:"Gaplashmoq; hikoya",on:'ワ',kun:'はな(す)',ex:'電話',em:"Telefon"},
  {k:'和',m:"Tinchlik; Yapon",on:'ワ',kun:'なご(む)',ex:'和食',em:"Yapon taomi"},
  {k:'足',m:"Oyoq; yetarli",on:'ソク',kun:'あし',ex:'足',em:"Oyoq"},
  {k:'頭',m:"Bosh; aql",on:'トウ・ズ',kun:'あたま・かしら',ex:'頭',em:"Bosh"},
  {k:'兄',m:"Katta aka",on:'ケイ・キョウ',kun:'あに',ex:'お兄さん',em:"Katta aka"},
  {k:'姉',m:"Katta opa",on:'シ',kun:'あね',ex:'お姉さん',em:"Katta opa"},
  {k:'雨',m:"Yomg'ir",on:'ウ',kun:'あめ',ex:'雨',em:"Yomg'ir"},
  {k:'犬',m:"It; kuchuk",on:'ケン',kun:'いぬ',ex:'犬',em:"It"},
  {k:'魚',m:"Baliq",on:'ギョ',kun:'さかな・うお',ex:'魚',em:"Baliq"},
  {k:'花',m:"Gul",on:'カ',kun:'はな',ex:'花見',em:"Gul tomoshasi"},
  {k:'木',m:"Daraxt; yog'och",on:'モク・ボク',kun:'き',ex:'木曜日',em:"Payshanba"},
  {k:'金',m:"Pul; oltin",on:'キン・コン',kun:'かね',ex:'お金',em:"Pul"},
  {k:'口',m:"Og'iz; eshik",on:'コウ・ク',kun:'くち',ex:'入口',em:"Kirish eshigi"},
  {k:'子',m:"Bola",on:'シ・ス',kun:'こ',ex:'子供',em:"Bola"},
  {k:'小',m:"Kichkina",on:'ショウ',kun:'ちい(さい)',ex:'小さい',em:"Kichkina"},
  {k:'上',m:"Tepada; yuqori",on:'ジョウ・ショウ',kun:'うえ・あ(げる)',ex:'上手',em:"Usta; mahoratli"},
  {k:'川',m:"Daryo",on:'セン',kun:'かわ',ex:'川',em:"Daryo"},
  {k:'千',m:"Ming",on:'セン',kun:'ち',ex:'千円',em:"Bir ming yen"},
  {k:'先',m:"Avval; uchi",on:'セン',kun:'さき',ex:'先生',em:"O'qituvchi"},
  {k:'早',m:"Erta; tez",on:'ソウ',kun:'はや(い)',ex:'早い',em:"Erta; tez"},
  {k:'男',m:"Erkak",on:'ダン・ナン',kun:'おとこ',ex:'男性',em:"Erkak"},
  {k:'中',m:"Ichida; markaz",on:'チュウ',kun:'なか',ex:'中学校',em:"O'rta maktab"},
  {k:'天',m:"Osmon",on:'テン',kun:'あめ・あま',ex:'天気',em:"Ob-havo"},
  {k:'東',m:"Sharq",on:'トウ',kun:'ひがし',ex:'東京',em:"Tokio"},
  {k:'南',m:"Janub",on:'ナン',kun:'みなみ',ex:'南',em:"Janub"},
  {k:'西',m:"G'arb",on:'セイ・サイ',kun:'にし',ex:'西',em:"G'arb"},
  {k:'日',m:"Kun; quyosh",on:'ニチ・ジツ',kun:'ひ',ex:'日曜日',em:"Yakshanba"},
  {k:'百',m:"Yuz",on:'ヒャク',kun:'—',ex:'百円',em:"Yuz yen"},
  {k:'目',m:"Ko'z; raqam",on:'モク・ボク',kun:'め',ex:'目',em:"Ko'z"},
  {k:'耳',m:"Quloq",on:'ジ',kun:'みみ',ex:'耳',em:"Quloq"},
  {k:'門',m:"Darvoza; eshik",on:'モン',kun:'かど',ex:'門',em:"Darvoza"},
  {k:'夕',m:"Kechqurun",on:'セキ',kun:'ゆう',ex:'夕方',em:"Kechki payt"},
  {k:'王',m:"Qirol; shoh",on:'オウ',kun:'—',ex:'王様',em:"Qirol"},
  {k:'右',m:"O'ng",on:'ウ・ユウ',kun:'みぎ',ex:'右手',em:"O'ng qo'l"},
  {k:'外',m:"Tashqari; xorijiy",on:'ガイ・ゲ',kun:'そと',ex:'外国',em:"Xorijiy mamlakat"},
  {k:'学',m:"O'rganmoq; maktab",on:'ガク',kun:'まな(ぶ)',ex:'大学',em:"Universitet"},
  {k:'間',m:"Oraliq; vaqt",on:'カン・ケン',kun:'あいだ',ex:'時間',em:"Vaqt"},
  {k:'帰',m:"Qaytmoq",on:'キ',kun:'かえ(る)',ex:'帰る',em:"Qaytib kelmoq"},
  {k:'休',m:"Dam olmoq",on:'キュウ',kun:'やす(む)',ex:'休み',em:"Dam olish"},
  {k:'去',m:"Ketmoq; o'tgan",on:'キョ・コ',kun:'さ(る)',ex:'去年',em:"O'tgan yil"},
  {k:'見',m:"Ko'rmoq",on:'ケン',kun:'み(る)',ex:'見る',em:"Ko'rmoq"},
  {k:'後',m:"Keyin; orqa",on:'ゴ・コウ',kun:'あと・のち',ex:'午後',em:"Tushdan keyin"},
  {k:'午',m:"Tush (12:00)",on:'ゴ',kun:'—',ex:'午前',em:"Ertalab"},
  {k:'細',m:"Ingichka; mayda",on:'サイ',kun:'ほそ(い)',ex:'細い',em:"Ingichka"},
  {k:'算',m:"Hisob; raqam",on:'サン',kun:'—',ex:'計算',em:"Hisoblash"},
  {k:'市',m:"Shahar",on:'シ',kun:'いち',ex:'市場',em:"Bozor"},
  {k:'室',m:"Xona; kabinet",on:'シツ',kun:'—',ex:'教室',em:"Sinf xonasi"},
  {k:'弱',m:"Kuchsiz",on:'ジャク',kun:'よわ(い)',ex:'弱い',em:"Kuchsiz"},
  {k:'主',m:"Egasi; asosiy",on:'シュ・ス',kun:'ぬし',ex:'主人',em:"Er; xo'jayin"},
  {k:'出',m:"Chiqmoq",on:'シュツ',kun:'で(る)',ex:'出口',em:"Chiqish"},
  {k:'春',m:"Bahor",on:'シュン',kun:'はる',ex:'春',em:"Bahor"},
  {k:'森',m:"O'rmon (katta)",on:'シン',kun:'もり',ex:'森',em:"Katta o'rmon"},
  {k:'心',m:"Yurak; qalb",on:'シン',kun:'こころ',ex:'心',em:"Qalb; yurak"},
  {k:'親',m:"Ota-ona; yaqin",on:'シン',kun:'おや',ex:'親',em:"Ota-ona"},
  {k:'晴',m:"Ochiq havo",on:'セイ',kun:'は(れる)',ex:'晴れ',em:"Ochiq havo"},
  {k:'雪',m:"Qor",on:'セツ',kun:'ゆき',ex:'雪',em:"Qor"},
  {k:'船',m:"Kema; qayiq",on:'セン',kun:'ふね',ex:'船',em:"Kema"},
  {k:'待',m:"Kutmoq",on:'タイ',kun:'ま(つ)',ex:'待つ',em:"Kutmoq"},
  {k:'竹',m:"Bambuk",on:'チク',kun:'たけ',ex:'竹',em:"Bambuk"},
  {k:'注',m:"Quymoq; e'tibor",on:'チュウ',kun:'そそ(ぐ)',ex:'注意',em:"E'tibor"},
  {k:'鳥',m:"Qush",on:'チョウ',kun:'とり',ex:'鳥',em:"Qush"},
  {k:'冬',m:"Qish",on:'トウ',kun:'ふゆ',ex:'冬',em:"Qish"},
  {k:'同',m:"Bir xil; birga",on:'ドウ',kun:'おな(じ)',ex:'同じ',em:"Bir xil"},
  {k:'動',m:"Harakatlanmoq",on:'ドウ',kun:'うご(く)',ex:'運動',em:"Harakat"},
  {k:'内',m:"Ichkarida",on:'ナイ・ダイ',kun:'うち',ex:'国内',em:"Mamlakat ichida"},
  {k:'売',m:"Sotmoq",on:'バイ',kun:'う(る)',ex:'売る',em:"Sotmoq"},
  {k:'発',m:"Chiqish; yubormoq",on:'ハツ・ホツ',kun:'は(つ)',ex:'出発',em:"Jo'nashmoq"},
  {k:'番',m:"Raqam; navbat",on:'バン',kun:'—',ex:'番号',em:"Raqam"},
  {k:'品',m:"Mahsulot; sifat",on:'ヒン',kun:'しな',ex:'品物',em:"Mahsulot"},
  {k:'部',m:"Bo'lim; qism",on:'ブ',kun:'—',ex:'部屋',em:"Xona"},
  {k:'歩',m:"Yurmoq; qadam",on:'ホ・ブ',kun:'ある(く)',ex:'歩く',em:"Yurmoq"},
  {k:'毎',m:"Har; har birida",on:'マイ',kun:'—',ex:'毎日',em:"Har kuni"},
  {k:'明',m:"Yorqin; tushunmoq",on:'メイ・ミョウ',kun:'あか(るい)',ex:'明日',em:"Ertaga"},
  {k:'横',m:"Yon; gorizontal",on:'オウ',kun:'よこ',ex:'横',em:"Yon"},
  {k:'弟',m:"Kichik aka (ukam)",on:'テイ・ダイ',kun:'おとうと',ex:'弟',em:"Ukam"},
  {k:'友',m:"Do'st",on:'ユウ',kun:'とも',ex:'友達',em:"Do'st"},
  {k:'開',m:"Ochmoq",on:'カイ',kun:'ひら(く)',ex:'開ける',em:"Ochmoq"},
  {k:'閉',m:"Yopmoq",on:'ヘイ',kun:'し(める)',ex:'閉める',em:"Yopmoq"},
  {k:'乗',m:"Minmoq",on:'ジョウ',kun:'の(る)',ex:'乗る',em:"Minmoq"},
  {k:'降',m:"Tushmoq; yog'moq",on:'コウ',kun:'お(りる)',ex:'降りる',em:"Tushmoq"},
  {k:'送',m:"Yubormoq",on:'ソウ',kun:'おく(る)',ex:'送る',em:"Yubormoq"},
  {k:'受',m:"Qabul qilmoq",on:'ジュ',kun:'う(ける)',ex:'受ける',em:"Qabul qilmoq"},
  {k:'持',m:"Ushlamoq; ega bo'lmoq",on:'ジ',kun:'も(つ)',ex:'持つ',em:"Ushlamoq"},
  {k:'集',m:"Yig'moq",on:'シュウ',kun:'あつ(める)',ex:'集める',em:"Yig'moq"},
  {k:'選',m:"Tanlash",on:'セン',kun:'えら(ぶ)',ex:'選ぶ',em:"Tanlash"},
  {k:'決',m:"Qaror qilmoq",on:'ケツ',kun:'き(める)',ex:'決める',em:"Qaror qilmoq"},
  {k:'払',m:"To'lamoq",on:'フツ',kun:'はら(う)',ex:'払う',em:"To'lamoq"},
  {k:'貸',m:"Qarz bermoq",on:'タイ',kun:'か(す)',ex:'貸す',em:"Qarz bermoq"},
  {k:'借',m:"Qarz olmoq",on:'シャク',kun:'か(りる)',ex:'借りる',em:"Qarz olmoq"},
  {k:'返',m:"Qaytarmoq",on:'ヘン',kun:'かえ(す)',ex:'返す',em:"Qaytarmoq"},
  {k:'取',m:"Olmoq; qo'lga kiritmoq",on:'シュ',kun:'と(る)',ex:'取る',em:"Olmoq"},
  {k:'置',m:"Qo'ymoq; joylamoq",on:'チ',kun:'お(く)',ex:'置く',em:"Qo'ymoq"},
  {k:'消',m:"O'chirmoq; yo'qolmoq",on:'ショウ',kun:'き(える)',ex:'消える',em:"Yo'qolmoq"},
  {k:'付',m:"Yopishmoq; biriktirmoq",on:'フ',kun:'つ(ける)',ex:'付ける',em:"Yopishmoq"},
  {k:'答',m:"Javob bermoq",on:'トウ',kun:'こた(える)',ex:'答える',em:"Javob bermoq"},
  {k:'質',m:"Sifat; savol",on:'シツ・シチ',kun:'—',ex:'質問',em:"Savol"},
  {k:'計',m:"Hisob; o'lchov",on:'ケイ',kun:'はか(る)',ex:'計画',em:"Reja"},
  {k:'一',m:"Bir",on:'イチ・イツ',kun:'ひと(つ)',ex:'一つ',em:"Bitta"},
  {k:'二',m:"Ikki",on:'ニ',kun:'ふた(つ)',ex:'二つ',em:"Ikkita"},
  {k:'三',m:"Uch",on:'サン',kun:'み(つ)',ex:'三つ',em:"Uchta"},
  {k:'四',m:"To'rt",on:'シ',kun:'よ(っつ)',ex:'四つ',em:"To'rtta"},
  {k:'五',m:"Besh",on:'ゴ',kun:'いつ(つ)',ex:'五つ',em:"Beshta"},
  {k:'六',m:"Olti",on:'ロク',kun:'む(っつ)',ex:'六つ',em:"Oltita"},
  {k:'七',m:"Yetti",on:'シチ',kun:'なな(つ)',ex:'七つ',em:"Yettita"},
  {k:'八',m:"Sakkiz",on:'ハチ',kun:'やっ(つ)',ex:'八つ',em:"Sakkizta"},
  {k:'九',m:"To'qqiz",on:'ク・キュウ',kun:'ここの(つ)',ex:'九つ',em:"To'qqizta"},
  {k:'十',m:"O'n",on:'ジュウ',kun:'とお',ex:'十分',em:"O'n daqiqa"},
  {k:'万',m:"O'n ming",on:'マン・バン',kun:'—',ex:'一万',em:"O'n ming"},
  {k:'円',m:"Yen; doira",on:'エン',kun:'まる(い)',ex:'百円',em:"Yuz yen"},
  {k:'月',m:"Oy; oy (osmon)",on:'ゲツ・ガツ',kun:'つき',ex:'月曜日',em:"Dushanba"},
  {k:'火',m:"Olov",on:'カ',kun:'ひ',ex:'火曜日',em:"Seshanba"},
  {k:'土',m:"Tuproq; er",on:'ド・ト',kun:'つち',ex:'土曜日',em:"Shanba"},
  {k:'手',m:"Qo'l",on:'シュ',kun:'て',ex:'手',em:"Qo'l"},
  {k:'鼻',m:"Burun",on:'ビ',kun:'はな',ex:'鼻',em:"Burun"},
  {k:'顔',m:"Yuz; aft",on:'ガン',kun:'かお',ex:'顔',em:"Yuz (bashara)"},
  {k:'首',m:"Bo'yin",on:'シュ',kun:'くび',ex:'首',em:"Bo'yin"},
  {k:'指',m:"Barmoq",on:'シ',kun:'ゆび',ex:'指',em:"Barmoq"},
  {k:'髪',m:"Soch",on:'ハツ',kun:'かみ',ex:'髪',em:"Soch"},
  {k:'歯',m:"Tish",on:'シ',kun:'は',ex:'歯',em:"Tish"},
  {k:'速',m:"Tez",on:'ソク',kun:'はや(い)',ex:'速い',em:"Tez"},
  {k:'遅',m:"Kech; sekin",on:'チ',kun:'おそ(い)',ex:'遅い',em:"Kech; sekin"},
  {k:'忙',m:"Band; shug'ul",on:'ボウ・モウ',kun:'いそが(しい)',ex:'忙しい',em:"Band"},
  {k:'暇',m:"Bo'sh vaqt",on:'カ',kun:'ひま',ex:'暇',em:"Bo'sh vaqt"},
  {k:'疲',m:"Charchagan",on:'ヒ',kun:'つか(れる)',ex:'疲れた',em:"Charchagan"},
  {k:'熱',m:"Issiq; harorat",on:'ネツ',kun:'あつ(い)',ex:'熱い',em:"Issiq (narsa)"},
  {k:'温',m:"Iliq; harorat",on:'オン',kun:'あたた(かい)',ex:'温かい',em:"Iliq"},
  {k:'涼',m:"Salqin; serin",on:'リョウ',kun:'すず(しい)',ex:'涼しい',em:"Salqin"},
  {k:'暑',m:"Issiq (havo)",on:'ショ',kun:'あつ(い)',ex:'暑い',em:"Issiq (havo)"},
  {k:'寒',m:"Sovuq (havo)",on:'カン',kun:'さむ(い)',ex:'寒い',em:"Sovuq (havo)"},
  {k:'広',m:"Keng",on:'コウ',kun:'ひろ(い)',ex:'広い',em:"Keng"},
  {k:'狭',m:"Tor; kichik",on:'キョウ',kun:'せま(い)',ex:'狭い',em:"Tor"},
  {k:'厚',m:"Qalin; mehribon",on:'コウ',kun:'あつ(い)',ex:'厚い',em:"Qalin"},
  {k:'薄',m:"Yupqa; siyrak",on:'ハク',kun:'うす(い)',ex:'薄い',em:"Yupqa"},
  {k:'重',m:"Og'ir; muhim",on:'ジュウ・チョウ',kun:'おも(い)',ex:'重い',em:"Og'ir"},
  {k:'固',m:"Qattiq; mustahkam",on:'コ',kun:'かた(い)',ex:'固い',em:"Qattiq"},
  {k:'若',m:"Yosh",on:'ジャク・ニャク',kun:'わか(い)',ex:'若い',em:"Yosh"},
  {k:'赤',m:"Qizil",on:'セキ・シャク',kun:'あか',ex:'赤い',em:"Qizil"},
  {k:'青',m:"Ko'k; yashil (o'simlik)",on:'セイ',kun:'あお',ex:'青い',em:"Ko'k"},
  {k:'黄',m:"Sariq",on:'コウ・オウ',kun:'き',ex:'黄色',em:"Sariq rang"},
  {k:'緑',m:"Yashil",on:'リョク',kun:'みどり',ex:'緑',em:"Yashil"},
  {k:'黒',m:"Qora",on:'コク',kun:'くろ',ex:'黒い',em:"Qora"},
  {k:'紫',m:"Binafsha",on:'シ',kun:'むらさき',ex:'紫',em:"Binafsha rang"},
  {k:'灰',m:"Kulrang; kul",on:'カイ',kun:'はい',ex:'灰色',em:"Kulrang"},
  {k:'雲',m:"Bulut",on:'ウン',kun:'くも',ex:'雲',em:"Bulut"},
  {k:'風',m:"Shamol",on:'フウ・フ',kun:'かぜ',ex:'台風',em:"Tayfun"},
  {k:'波',m:"To'lqin",on:'ハ',kun:'なみ',ex:'波',em:"To'lqin"},
  {k:'星',m:"Yulduz",on:'セイ・ショウ',kun:'ほし',ex:'星',em:"Yulduz"},
  {k:'光',m:"Nur; yorug'lik",on:'コウ',kun:'ひかり',ex:'光る',em:"Yaltirmoq"},
  {k:'影',m:"Soya; aks",on:'エイ',kun:'かげ',ex:'影',em:"Soya"},
  {k:'形',m:"Shakl; tur",on:'ケイ・ギョウ',kun:'かたち',ex:'形',em:"Shakl"},
  {k:'牛',m:"Sigir",on:'ギュウ',kun:'うし',ex:'牛乳',em:"Sut"},
  {k:'馬',m:"Ot (hayvon)",on:'バ',kun:'うま',ex:'馬',em:"Ot"},
  {k:'猫',m:"Mushuk",on:'ビョウ',kun:'ねこ',ex:'猫',em:"Mushuk"},
  {k:'虫',m:"Hasharot; qurt",on:'チュウ',kun:'むし',ex:'虫',em:"Hasharot"},
  {k:'羊',m:"Qo'y",on:'ヨウ',kun:'ひつじ',ex:'羊',em:"Qo'y"},
  {k:'鶏',m:"Tovuq",on:'ケイ',kun:'にわとり',ex:'鶏肉',em:"Tovuq go'shti"},
  {k:'真',m:"Haqiqiy; surat",on:'シン',kun:'ま',ex:'写真',em:"Surat"},
  {k:'図',m:"Rasm; xarita",on:'ズ・ト',kun:'—',ex:'地図',em:"Xarita"},
  {k:'絵',m:"Rasm; surat",on:'カイ',kun:'え',ex:'絵',em:"Rasm"},
  {k:'紙',m:"Qog'oz",on:'シ',kun:'かみ',ex:'手紙',em:"Xat"},
  {k:'服',m:"Kiyim",on:'フク',kun:'—',ex:'洋服',em:"Kiyim"},
  {k:'靴',m:"Poyafzal",on:'カ',kun:'くつ',ex:'靴',em:"Poyafzal"},
  {k:'箱',m:"Quti",on:'ソウ',kun:'はこ',ex:'箱',em:"Quti"},
  {k:'机',m:"Stol",on:'キ',kun:'つくえ',ex:'机',em:"Ish stoli"},
  {k:'棚',m:"Javon; tokcha",on:'ほう',kun:'たな',ex:'棚',em:"Javon"},
  {k:'窓',m:"Deraza",on:'ソウ',kun:'まど',ex:'窓',em:"Deraza"},
  {k:'壁',m:"Devor",on:'ヘキ',kun:'かべ',ex:'壁',em:"Devor"},
  {k:'橋',m:"Ko'prik",on:'キョウ',kun:'はし',ex:'橋',em:"Ko'prik"},
  {k:'坂',m:"Tepalik; qiya",on:'ハン',kun:'さか',ex:'坂道',em:"Qiya yo'l"},
  {k:'池',m:"Ko'l; hovuz",on:'チ',kun:'いけ',ex:'池',em:"Hovuz"},
  {k:'島',m:"Orol",on:'トウ',kun:'しま',ex:'島',em:"Orol"},
  {k:'村',m:"Qishloq",on:'ソン',kun:'むら',ex:'村',em:"Qishloq"},
  {k:'町',m:"Shahar (kichik)",on:'チョウ',kun:'まち',ex:'町',em:"Mahalla"},
  {k:'都',m:"Poytaxt; shahar",on:'ト・ツ',kun:'みやこ',ex:'都市',em:"Shahar"},
  {k:'区',m:"Tuman; mintaqa",on:'ク',kun:'—',ex:'区',em:"Tuman"},
  {k:'特',m:"Maxsus; alohida",on:'トク',kun:'—',ex:'特別',em:"Alohida; maxsus"},
  {k:'普',m:"Oddiy; odatiy",on:'フ',kun:'—',ex:'普通',em:"Oddiy"},
  {k:'例',m:"Misol",on:'レイ',kun:'たと(える)',ex:'例えば',em:"Masalan"},
  {k:'用',m:"Ishlatmoq; maqsad",on:'ヨウ',kun:'もち(いる)',ex:'使用',em:"Ishlatish"},
  {k:'産',m:"Ishlab chiqarish; tug'moq",on:'サン',kun:'う(む)',ex:'産業',em:"Sanoat"},
  {k:'民',m:"Xalq; fuqaro",on:'ミン',kun:'たみ',ex:'国民',em:"Davlat xalqi"},
  {k:'農',m:"Dehqonchilik",on:'ノウ',kun:'—',ex:'農業',em:"Qishloq xo'jaligi"},
  {k:'研',m:"Tekshirmoq; o'tkirlamoq",on:'ケン',kun:'と(ぐ)',ex:'研究',em:"Tadqiqot"},
  {k:'究',m:"O'rganmoq; chuqur qazmoq",on:'キュウ',kun:'きわ(める)',ex:'研究',em:"Tadqiqot"},
  {k:'秒',m:"Soniya",on:'ビョウ',kun:'—',ex:'三十秒',em:"O'ttiz soniya"},
  {k:'度',m:"Daraja; marta",on:'ド',kun:'たび',ex:'温度',em:"Harorat"},
  {k:'腕',m:"Bilak; qo'l (yelka pastidan)",on:'ワン',kun:'うで',ex:'腕',em:"Bilak"},
  {k:'血',m:"Qon",on:'ケツ',kun:'ち',ex:'血',em:"Qon"},
  {k:'息',m:"Nafas; o'g'il",on:'ソク',kun:'いき',ex:'息子',em:"O'g'il"},
  {k:'病',m:"Kasallik",on:'ビョウ・ヘイ',kun:'やまい',ex:'病院',em:"Shifoxona"},
  {k:'痛',m:"Og'riq; og'riqli",on:'ツウ',kun:'いた(い)',ex:'頭痛',em:"Bosh og'riq"},
  {k:'危',m:"Xavfli",on:'キ',kun:'あぶ(ない)',ex:'危ない',em:"Xavfli"},
  {k:'笑',m:"Kulmoq",on:'ショウ',kun:'わら(う)',ex:'笑う',em:"Kulmoq"},
  {k:'泣',m:"Yig'lamoq",on:'キュウ',kun:'な(く)',ex:'泣く',em:"Yig'lamoq"},
  {k:'怒',m:"G'azablanmoq",on:'ド',kun:'おこ(る)',ex:'怒る',em:"G'azablanmoq"},
  {k:'喜',m:"Xursand bo'lmoq",on:'キ',kun:'よろこ(ぶ)',ex:'喜ぶ',em:"Xursand bo'lmoq"},
  {k:'悲',m:"Qayg'urmoq; g'amgin",on:'ヒ',kun:'かな(しい)',ex:'悲しい',em:"G'amgin"},
  {k:'困',m:"Qiynalmoq; muammo",on:'コン',kun:'こま(る)',ex:'困る',em:"Qiynalmoq"},
  {k:'終',m:"Tugamoq; oxir",on:'シュウ',kun:'お(わる)',ex:'終わる',em:"Tugamoq"},
  {k:'変',m:"O'zgarmoq; g'alati",on:'ヘン',kun:'か(わる)',ex:'変わる',em:"O'zgarmoq"},
  {k:'止',m:"To'xtatmoq",on:'シ',kun:'と(まる)',ex:'止まる',em:"To'xtamoq"},
];

// Deduplicate by kanji character
const _seen = new Set();
const KANJI_DATA = KANJI_RAW.filter(x => {
  if (_seen.has(x.k)) return false;
  _seen.add(x.k);
  return true;
});

// ============================================================
//  KATAKANA CHART
// ============================================================
const KATA_CHART = [
  { row: 'ア行', chars: [
    {c:'ア',r:'a'},{c:'イ',r:'i'},{c:'ウ',r:'u'},{c:'エ',r:'e'},{c:'オ',r:'o'}
  ]},
  { row: 'カ行', chars: [
    {c:'カ',r:'ka'},{c:'キ',r:'ki'},{c:'ク',r:'ku'},{c:'ケ',r:'ke'},{c:'コ',r:'ko'}
  ]},
  { row: 'サ行', chars: [
    {c:'サ',r:'sa'},{c:'シ',r:'shi'},{c:'ス',r:'su'},{c:'セ',r:'se'},{c:'ソ',r:'so'}
  ]},
  { row: 'タ行', chars: [
    {c:'タ',r:'ta'},{c:'チ',r:'chi'},{c:'ツ',r:'tsu'},{c:'テ',r:'te'},{c:'ト',r:'to'}
  ]},
  { row: 'ナ行', chars: [
    {c:'ナ',r:'na'},{c:'ニ',r:'ni'},{c:'ヌ',r:'nu'},{c:'ネ',r:'ne'},{c:'ノ',r:'no'}
  ]},
  { row: 'ハ行', chars: [
    {c:'ハ',r:'ha'},{c:'ヒ',r:'hi'},{c:'フ',r:'fu'},{c:'ヘ',r:'he'},{c:'ホ',r:'ho'}
  ]},
  { row: 'マ行', chars: [
    {c:'マ',r:'ma'},{c:'ミ',r:'mi'},{c:'ム',r:'mu'},{c:'メ',r:'me'},{c:'モ',r:'mo'}
  ]},
  { row: 'ヤ行', chars: [
    {c:'ヤ',r:'ya'},{c:'ユ',r:'yu'},{c:'ヨ',r:'yo'}
  ]},
  { row: 'ラ行', chars: [
    {c:'ラ',r:'ra'},{c:'リ',r:'ri'},{c:'ル',r:'ru'},{c:'レ',r:'re'},{c:'ロ',r:'ro'}
  ]},
  { row: 'ワ行', chars: [
    {c:'ワ',r:'wa'},{c:'ヲ',r:'wo'},{c:'ン',r:'n'}
  ]},
  { row: 'ガ行 (Voiced)', chars: [
    {c:'ガ',r:'ga'},{c:'ギ',r:'gi'},{c:'グ',r:'gu'},{c:'ゲ',r:'ge'},{c:'ゴ',r:'go'}
  ]},
  { row: 'ザ行 (Voiced)', chars: [
    {c:'ザ',r:'za'},{c:'ジ',r:'ji'},{c:'ズ',r:'zu'},{c:'ゼ',r:'ze'},{c:'ゾ',r:'zo'}
  ]},
  { row: 'ダ行 (Voiced)', chars: [
    {c:'ダ',r:'da'},{c:'ヂ',r:'ji'},{c:'ヅ',r:'zu'},{c:'デ',r:'de'},{c:'ド',r:'do'}
  ]},
  { row: 'バ行 (Voiced)', chars: [
    {c:'バ',r:'ba'},{c:'ビ',r:'bi'},{c:'ブ',r:'bu'},{c:'ベ',r:'be'},{c:'ボ',r:'bo'}
  ]},
  { row: 'パ行 (Semi-voiced)', chars: [
    {c:'パ',r:'pa'},{c:'ピ',r:'pi'},{c:'プ',r:'pu'},{c:'ペ',r:'pe'},{c:'ポ',r:'po'}
  ]},
];

// ============================================================
//  KATAKANA WORDS
// ============================================================
const KATA_WORDS = [
  {w:'アイスクリーム',r:'aisukuriimu',m:"Muzqaymoq"},
  {w:'アパート',r:'apaato',m:"Kvartira"},
  {w:'アメリカ',r:'Amerika',m:"Amerika"},
  {w:'イギリス',r:'Igirisu',m:"Angliya"},
  {w:'イタリア',r:'Itaria',m:"Italiya"},
  {w:'インターネット',r:'intaanetto',m:"Internet"},
  {w:'インタビュー',r:'intabyuu',m:"Intervyu"},
  {w:'ウイスキー',r:'uisukii',m:"Viski"},
  {w:'エアコン',r:'eakon',m:"Konditsioner"},
  {w:'エネルギー',r:'enerugii',m:"Energiya"},
  {w:'オレンジ',r:'orenji',m:"Apelsin"},
  {w:'オフィス',r:'ofisu',m:"Ofis"},
  {w:'カメラ',r:'kamera',m:"Kamera"},
  {w:'カレンダー',r:'karendaa',m:"Taqvim"},
  {w:'カレー',r:'karii',m:"Kari (taom)"},
  {w:'カーテン',r:'kaaten',m:"Parda"},
  {w:'カード',r:'kaado',m:"Karta"},
  {w:'ガラス',r:'garasu',m:"Shisha"},
  {w:'キッチン',r:'kicchin',m:"Oshxona"},
  {w:'キャベツ',r:'kyabetsu',m:"Karam"},
  {w:'キャンプ',r:'kyanpu',m:"Lager (kemping)"},
  {w:'ギター',r:'gitaa',m:"Gitara"},
  {w:'クラス',r:'kurasu',m:"Sinf"},
  {w:'クラブ',r:'kurabu',m:"Klub"},
  {w:'クリーム',r:'kuriimu',m:"Krem"},
  {w:'コート',r:'kooto',m:"Palto"},
  {w:'コーヒー',r:'koohii',m:"Kofe"},
  {w:'コップ',r:'koppu',m:"Stakan"},
  {w:'コピー',r:'kopii',m:"Nusxa"},
  {w:'コンピューター',r:'konpyuutaa',m:"Kompyuter"},
  {w:'サッカー',r:'sakkaa',m:"Futbol"},
  {w:'サンドイッチ',r:'sandoicchi',m:"Sendvich"},
  {w:'サービス',r:'saabisu',m:"Xizmat"},
  {w:'システム',r:'shisutemu',m:"Sistema"},
  {w:'シャツ',r:'shatsu',m:"Ko'ylak"},
  {w:'シャワー',r:'shawaa',m:"Dush"},
  {w:'ジャケット',r:'jaketto',m:"Jaket"},
  {w:'ジュース',r:'juusu',m:"Sharbat"},
  {w:'スカート',r:'sukaato',m:"Yubka"},
  {w:'スキー',r:'sukii',m:"Chang'i"},
  {w:'スプーン',r:'supuun',m:"Qoshiq"},
  {w:'スポーツ',r:'supootsu',m:"Sport"},
  {w:'スマホ',r:'sumaho',m:"Smartfon"},
  {w:'セーター',r:'seetaa',m:"Sviter"},
  {w:'センター',r:'sentaa',m:"Markaz"},
  {w:'ソファ',r:'sofa',m:"Divan"},
  {w:'タクシー',r:'takushii',m:"Taksi"},
  {w:'タオル',r:'taoru',m:"Sochiq"},
  {w:'ダンス',r:'dansu',m:"Raqs"},
  {w:'チーズ',r:'chiizu',m:"Pishloq"},
  {w:'チケット',r:'chiketto',m:"Chipta"},
  {w:'テーブル',r:'teebburu',m:"Stol"},
  {w:'テレビ',r:'terebi',m:"Televizor"},
  {w:'デパート',r:'depaato',m:"Univermag"},
  {w:'データ',r:'deeta',m:"Ma'lumot"},
  {w:'トイレ',r:'toire',m:"Hojatxona"},
  {w:'トマト',r:'tomato',m:"Pomidor"},
  {w:'ドア',r:'doa',m:"Eshik"},
  {w:'ドレス',r:'doresu',m:"Ko'ylak (ayollar)"},
  {w:'ナイフ',r:'naifu',m:"Pichoq"},
  {w:'ナース',r:'naasuː',m:"Hamshira"},
  {w:'ニュース',r:'nyuusu',m:"Yangiliklar"},
  {w:'ネクタイ',r:'nekutai',m:"Galstuk"},
  {w:'ノート',r:'nooto',m:"Daftar"},
  {w:'パーティー',r:'paatii',m:"Ziyofat"},
  {w:'パソコン',r:'pasokon',m:"Shaxsiy kompyuter"},
  {w:'パン',r:'pan',m:"Non"},
  {w:'ピアノ',r:'piano',m:"Pianino"},
  {w:'ビール',r:'biiru',m:"Pivo"},
  {w:'ビル',r:'biru',m:"Bino; ko'p qavatli"},
  {w:'ファイル',r:'fairu',m:"Fayl"},
  {w:'フィルム',r:'firumu',m:"Film"},
  {w:'フォーク',r:'fooku',m:"Vilka"},
  {w:'フランス',r:'Furansu',m:"Fransiya"},
  {w:'ブラウス',r:'burausu',m:"Bluzka"},
  {w:'プール',r:'puuru',m:"Basseyn"},
  {w:'プレゼント',r:'purezento',m:"Sovg'a"},
  {w:'プログラム',r:'puroguramu',m:"Dastur"},
  {w:'ベッド',r:'beddo',m:"Karavot"},
  {w:'ベルト',r:'beruto',m:"Kamar"},
  {w:'ペン',r:'pen',m:"Qalam (ruchka)"},
  {w:'ペット',r:'petto',m:"Uy hayvoni"},
  {w:'ホテル',r:'hoteru',m:"Mehmonxona"},
  {w:'ボール',r:'booru',m:"To'p"},
  {w:'ボタン',r:'botan',m:"Tugma"},
  {w:'マスク',r:'masuku',m:"Niqob"},
  {w:'マンション',r:'manshon',m:"Kvartira (yuqori sifatli)"},
  {w:'ミルク',r:'miruku',m:"Sut"},
  {w:'メガネ',r:'megane',m:"Ko'zoynak"},
  {w:'メニュー',r:'menyuu',m:"Menyu"},
  {w:'モデル',r:'moderu',m:"Model"},
  {w:'ラーメン',r:'raamen',m:"Ramen (tayyor sho'rva)"},
  {w:'ラジオ',r:'rajio',m:"Radio"},
  {w:'リスト',r:'risuto',m:"Ro'yxat"},
  {w:'リンゴ',r:'ringo',m:"Olma"},
  {w:'レストラン',r:'resutoran',m:"Restoran"},
  {w:'レポート',r:'repooto',m:"Hisobot"},
  {w:'レモン',r:'remon',m:"Limon"},
  {w:'ロボット',r:'robotto',m:"Robot"},
  {w:'ワイン',r:'wain',m:"Vino"},
  {w:'アクセス',r:'akusesu',m:"Kirish; yo'l"},
  {w:'アドレス',r:'adoresu',m:"Manzil"},
  {w:'アニメ',r:'anime',m:"Anime"},
  {w:'アルバイト',r:'arubaito',m:"Qo'shimcha ish"},
  {w:'イメージ',r:'imeeji',m:"Taassurot"},
  {w:'イベント',r:'ibento',m:"Tadbir"},
  {w:'ウェブ',r:'webu',m:"Veb (internet)"},
  {w:'エンジン',r:'enjin',m:"Dvigatel"},
  {w:'オーダー',r:'oodaa',m:"Buyurtma"},
  {w:'オプション',r:'opushon',m:"Imkoniyat"},
  {w:'カタログ',r:'katarogu',m:"Katalog"},
  {w:'カバー',r:'kabaa',m:"Muqova"},
  {w:'キーワード',r:'kiiwado',m:"Kalit so'z"},
  {w:'キャリア',r:'kyaria',m:"Karyera"},
  {w:'クイズ',r:'kuizu',m:"Viktorina"},
  {w:'クレジット',r:'kurejitto',m:"Kredit"},
  {w:'ケース',r:'keesu',m:"Hol; quti"},
  {w:'コース',r:'koosu',m:"Kurs; yo'nalish"},
  {w:'コメント',r:'komento',m:"Izoh"},
  {w:'コンセプト',r:'konseputo',m:"Konsepsiya"},
  {w:'サイト',r:'saito',m:"Sayt"},
  {w:'サンプル',r:'sanpuru',m:"Namuna"},
  {w:'シーン',r:'shiin',m:"Sahna"},
  {w:'ショップ',r:'shoppu',m:"Do'kon"},
  {w:'スケジュール',r:'sukejuuru',m:"Jadval"},
  {w:'スタイル',r:'sutairu',m:"Uslub"},
  {w:'スタッフ',r:'sutaffu',m:"Xodimlar"},
  {w:'ストレス',r:'sutoresu',m:"Stress"},
  {w:'セット',r:'setto',m:"To'plam"},
  {w:'センス',r:'sensu',m:"Did"},
  {w:'ソフト',r:'sofuto',m:"Dasturiy ta'minot"},
  {w:'タイプ',r:'taipu',m:"Tur"},
  {w:'タイトル',r:'taitoru',m:"Sarlavha"},
  {w:'チャレンジ',r:'charenji',m:"Musobaqa; qiyinchilikka borish"},
  {w:'テーマ',r:'teema',m:"Mavzu"},
  {w:'テクニック',r:'tekunikku',m:"Texnika"},
  {w:'デザイン',r:'dezain',m:"Dizayn"},
  {w:'トラブル',r:'toraburu',m:"Muammo"},
  {w:'トレーニング',r:'toreeningu',m:"Trening"},
  {w:'ドリンク',r:'dorinku',m:"Ichimlik"},
  {w:'ナンバー',r:'nanbaa',m:"Raqam"},
  {w:'ニーズ',r:'niizu',m:"Ehtiyoj"},
  {w:'ネットワーク',r:'nettowaaku',m:"Tarmoq"},
  {w:'ノイズ',r:'noizu',m:"Shovqin"},
  {w:'パターン',r:'pataaan',m:"Shablon"},
  {w:'パワー',r:'pawaa',m:"Quvvat"},
  {w:'ビジネス',r:'bijinesu',m:"Biznes"},
  {w:'ファッション',r:'fasshon',m:"Moda"},
  {w:'フィードバック',r:'fiidoobakku',m:"Fikr-mulohaza"},
  {w:'フォーマット',r:'foomatto',m:"Format"},
  {w:'ブランド',r:'burando',m:"Brend"},
  {w:'プラン',r:'puran',m:"Reja"},
  {w:'プロジェクト',r:'purojekuto',m:"Loyiha"},
  {w:'ベース',r:'beesu',m:"Asos"},
  {w:'ペース',r:'peesu',m:"Tezlik; sur'at"},
  {w:'ホームページ',r:'hoomu peeji',m:"Veb-sahifa"},
  {w:'ボリューム',r:'boryuumu',m:"Hajm"},
  {w:'マネージャー',r:'maneejaa',m:"Menejer"},
  {w:'ミーティング',r:'miitingu',m:"Yig'ilish"},
  {w:'メッセージ',r:'messeeji',m:"Xabar"},
  {w:'モニター',r:'monitaa',m:"Monitor"},
  {w:'ユーザー',r:'yuuzaa',m:"Foydalanuvchi"},
  {w:'ライフ',r:'raifu',m:"Hayot"},
  {w:'ランク',r:'ranku',m:"Daraja"},
  {w:'リスク',r:'risuku',m:"Xavf"},
  {w:'リーダー',r:'riidaa',m:"Lider"},
  {w:'レベル',r:'reberu',m:"Daraja"},
  {w:'ログイン',r:'roguin',m:"Tizimga kirish"},
  {w:'ワーク',r:'waaku',m:"Ish"},
  {w:'アラーム',r:'araamu',m:"Signal"},
  {w:'ウイルス',r:'uirusu',m:"Virus"},
  {w:'エラー',r:'eraa',m:"Xato"},
  {w:'オンライン',r:'onrain',m:"Onlayn"},
  {w:'カスタマー',r:'kasutamaa',m:"Mijoz"},
  {w:'キャンセル',r:'kyanseru',m:"Bekor qilish"},
  {w:'コントロール',r:'kontororu',m:"Nazorat"},
  {w:'サーバー',r:'saabaa',m:"Server"},
  {w:'シェア',r:'shea',m:"Ulush"},
  {w:'ストック',r:'sutokku',m:"Zaxira"},
  {w:'スピード',r:'supiido',m:"Tezlik"},
  {w:'セキュリティ',r:'sekyuriti',m:"Xavfsizlik"},
  {w:'ソリューション',r:'soryuushon',m:"Yechim"},
  {w:'ターゲット',r:'taagetto',m:"Maqsad"},
  {w:'チーム',r:'chiimu',m:"Jamoa"},
  {w:'デバイス',r:'debaisu',m:"Qurilma"},
  {w:'トラック',r:'torakku',m:"Yo'l; trek"},
  {w:'ドキュメント',r:'dokyumento',m:"Hujjat"},
  {w:'ナビ',r:'nabi',m:"Navigatsiya"},
  {w:'ネーム',r:'neemu',m:"Ism"},
  {w:'パスワード',r:'pasuwaado',m:"Parol"},
  {w:'パートナー',r:'paatonaa',m:"Hamkor"},
  {w:'ビジョン',r:'bijon',m:"Ko'rinish; maqsad"},
  {w:'フレーム',r:'fureemu',m:"Ramka"},
  {w:'プロセス',r:'purosesu',m:"Jarayon"},
  {w:'メソッド',r:'mesoddo',m:"Usul"},
];

/* ============================================================
   HIRAGANA DATA
============================================================ */
const HIRA_CHART = [
  { row: 'あ行', chars: [{c:'あ',r:'a'},{c:'い',r:'i'},{c:'う',r:'u'},{c:'え',r:'e'},{c:'お',r:'o'}] },
  { row: 'か行', chars: [{c:'か',r:'ka'},{c:'き',r:'ki'},{c:'く',r:'ku'},{c:'け',r:'ke'},{c:'こ',r:'ko'}] },
  { row: 'さ行', chars: [{c:'さ',r:'sa'},{c:'し',r:'shi'},{c:'す',r:'su'},{c:'せ',r:'se'},{c:'そ',r:'so'}] },
  { row: 'た行', chars: [{c:'た',r:'ta'},{c:'ち',r:'chi'},{c:'つ',r:'tsu'},{c:'て',r:'te'},{c:'と',r:'to'}] },
  { row: 'な行', chars: [{c:'な',r:'na'},{c:'に',r:'ni'},{c:'ぬ',r:'nu'},{c:'ね',r:'ne'},{c:'の',r:'no'}] },
  { row: 'は行', chars: [{c:'は',r:'ha'},{c:'ひ',r:'hi'},{c:'ふ',r:'fu'},{c:'へ',r:'he'},{c:'ほ',r:'ho'}] },
  { row: 'ま行', chars: [{c:'ま',r:'ma'},{c:'み',r:'mi'},{c:'む',r:'mu'},{c:'め',r:'me'},{c:'も',r:'mo'}] },
  { row: 'や行', chars: [{c:'や',r:'ya'},{c:'ゆ',r:'yu'},{c:'よ',r:'yo'}] },
  { row: 'ら行', chars: [{c:'ら',r:'ra'},{c:'り',r:'ri'},{c:'る',r:'ru'},{c:'れ',r:'re'},{c:'ろ',r:'ro'}] },
  { row: 'わ行', chars: [{c:'わ',r:'wa'},{c:'を',r:'wo'},{c:'ん',r:'n'}] },
  { row: 'が行 (dakuten)', chars: [{c:'が',r:'ga'},{c:'ぎ',r:'gi'},{c:'ぐ',r:'gu'},{c:'げ',r:'ge'},{c:'ご',r:'go'}] },
  { row: 'ざ行', chars: [{c:'ざ',r:'za'},{c:'じ',r:'ji'},{c:'ず',r:'zu'},{c:'ぜ',r:'ze'},{c:'ぞ',r:'zo'}] },
  { row: 'だ行', chars: [{c:'だ',r:'da'},{c:'ぢ',r:'ji'},{c:'づ',r:'zu'},{c:'で',r:'de'},{c:'ど',r:'do'}] },
  { row: 'ば行', chars: [{c:'ば',r:'ba'},{c:'び',r:'bi'},{c:'ぶ',r:'bu'},{c:'べ',r:'be'},{c:'ぼ',r:'bo'}] },
  { row: 'ぱ行 (handakuten)', chars: [{c:'ぱ',r:'pa'},{c:'ぴ',r:'pi'},{c:'ぷ',r:'pu'},{c:'ぺ',r:'pe'},{c:'ぽ',r:'po'}] },
];

const HIRA_WORDS = [
  {w:'あめ',r:'ame',m:'Yomg\'ir'},{w:'いぬ',r:'inu',m:'It'},{w:'うみ',r:'umi',m:'Dengiz'},
  {w:'えき',r:'eki',m:'Stansiya'},{w:'おかね',r:'okane',m:'Pul'},{w:'かさ',r:'kasa',m:'Soyabon'},
  {w:'きって',r:'kitte',m:'Marka (pochta)'},{w:'くに',r:'kuni',m:'Mamlakat'},{w:'けいたい',r:'keitai',m:'Mobil telefon'},
  {w:'こうえん',r:'kouen',m:'Park'},{w:'さかな',r:'sakana',m:'Baliq'},{w:'しごと',r:'shigoto',m:'Ish'},
  {w:'すし',r:'sushi',m:'Sushi'},{w:'せんせい',r:'sensei',m:'O\'qituvchi'},{w:'そら',r:'sora',m:'Osmon'},
  {w:'たべもの',r:'tabemono',m:'Taom'},{w:'ちず',r:'chizu',m:'Xarita'},{w:'つき',r:'tsuki',m:'Oy (osmon)'},
  {w:'てがみ',r:'tegami',m:'Xat'},{w:'ともだち',r:'tomodachi',m:'Do\'st'},{w:'なまえ',r:'namae',m:'Ism'},
  {w:'にほん',r:'nihon',m:'Yaponiya'},{w:'ねこ',r:'neko',m:'Mushuk'},{w:'のみもの',r:'nomimono',m:'Ichimlik'},
  {w:'はな',r:'hana',m:'Gul'},{w:'ひと',r:'hito',m:'Odam'},{w:'ふね',r:'fune',m:'Kema'},
  {w:'へや',r:'heya',m:'Xona'},{w:'ほん',r:'hon',m:'Kitob'},{w:'まち',r:'machi',m:'Shahar'},
  {w:'みず',r:'mizu',m:'Suv'},{w:'むすこ',r:'musuko',m:'O\'g\'il'},{w:'めがね',r:'megane',m:'Ko\'zoynak'},
  {w:'もり',r:'mori',m:'O\'rmon'},{w:'やま',r:'yama',m:'Tog\''},{w:'ゆき',r:'yuki',m:'Qor'},
  {w:'よる',r:'yoru',m:'Kecha'},{w:'りんご',r:'ringo',m:'Olma'},{w:'るすばんでんわ',r:'rusuban denwa',m:'Avtomatik javob beruvchi'},
  {w:'れんしゅう',r:'renshuu',m:'Mashq'},{w:'ろうか',r:'rouka',m:'Yo\'lak'},{w:'わたし',r:'watashi',m:'Men'},
];

/* ============================================================
   MINI STORIES DATA
============================================================ */
const STORIES = [
  {
    title: '☕ Kissaten de',
    titleJp: '喫茶店で',
    level: 'N4',
    words: [
      {jp:'私',r:'watashi',m:'Men'},{jp:'は',r:'wa',m:'(mavzu belgisi)'},{jp:'毎朝',r:'maiasa',m:'Har ertalab'},
      {jp:'喫茶店',r:'kissaten',m:'Qahvaxona'},{jp:'に',r:'ni',m:'(joy belgisi)'},{jp:'行きます',r:'ikimasu',m:'Boraman'},
      {jp:'。',r:'',m:''},{jp:'コーヒー',r:'koohii',m:'Qahva'},{jp:'を',r:'wo',m:'(ob\'ekt belgisi'},
      {jp:'飲みながら',r:'nominagara',m:'Ichib turgancha'},{jp:'、',r:'',m:''},{jp:'本',r:'hon',m:'Kitob'},
      {jp:'を',r:'wo',m:'(ob\'ekt belgisi)'},{jp:'読みます',r:'yomimasu',m:'O\'qiyman'},{jp:'。',r:'',m:''},
      {jp:'とても',r:'totemo',m:'Juda'},{jp:'静か',r:'shizuka',m:'Tinch'},{jp:'で',r:'de',m:'va (sifat bog\'lovchi)'},
      {jp:'好き',r:'suki',m:'Yaxshi ko\'raman'},{jp:'です',r:'desu',m:'(iltifot)'},{jp:'。',r:'',m:''},
    ],
    translation: 'Men har ertalab qahvaxonaga boraman. Qahva icharkan, kitob o\'qiyman. Juda tinch — yaxshi ko\'raman.'
  },
  {
    title: '🛒 Supa de kaimono',
    titleJp: 'スーパーで買い物',
    level: 'N4',
    words: [
      {jp:'今日',r:'kyou',m:'Bugun'},{jp:'、',r:'',m:''},{jp:'母',r:'haha',m:'Onam'},{jp:'と',r:'to',m:'bilan'},
      {jp:'スーパー',r:'suupaa',m:'Supermarket'},{jp:'に',r:'ni',m:'ga'},{jp:'行きました',r:'ikimashita',m:'bordik'},
      {jp:'。',r:'',m:''},{jp:'野菜',r:'yasai',m:'Sabzavot'},{jp:'と',r:'to',m:'va'},{jp:'果物',r:'kudamono',m:'Meva'},
      {jp:'を',r:'wo',m:'(ob\'ekt)'},{jp:'買いました',r:'kaimashita',m:'sotib oldik'},{jp:'。',r:'',m:''},
      {jp:'リンゴ',r:'ringo',m:'Olma'},{jp:'が',r:'ga',m:'(mavzu)'},{jp:'安かった',r:'yasukatta',m:'arzon edi'},
      {jp:'ので',r:'node',m:'shuning uchun'},{jp:'、',r:'',m:''},{jp:'たくさん',r:'takusan',m:'ko\'p'},
      {jp:'買いました',r:'kaimashita',m:'sotib oldik'},{jp:'。',r:'',m:''},
    ],
    translation: 'Bugun onam bilan supermarketga bordik. Sabzavot va meva sotib oldik. Olmalar arzon edi, shuning uchun ko\'p oldik.'
  },
  {
    title: '🌸 Haru no kouen',
    titleJp: '春の公園',
    level: 'N4',
    words: [
      {jp:'春',r:'haru',m:'Bahor'},{jp:'に',r:'ni',m:'da'},{jp:'なると',r:'naruto',m:'kelganda'},
      {jp:'、',r:'',m:''},{jp:'公園',r:'kouen',m:'Park'},{jp:'の',r:'no',m:'ning'},{jp:'桜',r:'sakura',m:'Gilos guli'},
      {jp:'が',r:'ga',m:'(mavzu)'},{jp:'きれい',r:'kirei',m:'chiroyli'},{jp:'に',r:'ni',m:'tarzda'},
      {jp:'咲きます',r:'sakimasu',m:'ochiladi'},{jp:'。',r:'',m:''},{jp:'子供たち',r:'kodomotachi',m:'Bolalar'},
      {jp:'が',r:'ga',m:''},{jp:'楽しそうに',r:'tanoshisou ni',m:'quvnoq tarzda'},{jp:'遊んでいます',r:'asonde imasu',m:'o\'ynayapti'},
      {jp:'。',r:'',m:''},{jp:'本当に',r:'hontou ni',m:'Haqiqatan'},{jp:'素晴らしい',r:'subarashii',m:'ajoyib'},
      {jp:'季節',r:'kisetsu',m:'fasl'},{jp:'です',r:'desu',m:''},{jp:'。',r:'',m:''},
    ],
    translation: 'Bahor kelganda, parkdagi gilos gullari chiroyli ochiladi. Bolalar quvnoq o\'ynayapti. Haqiqatan ajoyib fasl.'
  },
  {
    title: '📚 Toshokan de benkyou',
    titleJp: '図書館で勉強',
    level: 'N4',
    words: [
      {jp:'試験',r:'shiken',m:'Imtihon'},{jp:'の',r:'no',m:'ning'},{jp:'前',r:'mae',m:'oldin'},
      {jp:'、',r:'',m:''},{jp:'図書館',r:'toshokan',m:'Kutubxona'},{jp:'で',r:'de',m:'da'},
      {jp:'勉強',r:'benkyou',m:'O\'qish'},{jp:'します',r:'shimasu',m:'qilaman'},{jp:'。',r:'',m:''},
      {jp:'静か',r:'shizuka',m:'Tinch'},{jp:'な',r:'na',m:'(sifat bog\'lovchi)'},{jp:'場所',r:'basho',m:'joy'},
      {jp:'なので',r:'nanode',m:'bo\'lgani uchun'},{jp:'、',r:'',m:''},{jp:'集中',r:'shuuchuu',m:'Diqqat'},
      {jp:'できます',r:'dekimasu',m:'qila olaman'},{jp:'。',r:'',m:''},{jp:'友達',r:'tomodachi',m:'Do\'st'},
      {jp:'と',r:'to',m:'bilan'},{jp:'一緒に',r:'issho ni',m:'birga'},{jp:'行く',r:'iku',m:'boraman'},
      {jp:'こともあります',r:'koto mo arimasu',m:'ham bo\'ladi'},{jp:'。',r:'',m:''},
    ],
    translation: 'Imtihon oldidan kutubxonada o\'qiyman. Tinch joy bo\'lgani uchun diqqat qila olaman. Do\'stim bilan birga borgan ham bo\'ladi.'
  },
  {
    title: '🍜 Resutoran de',
    titleJp: 'レストランで',
    level: 'N4',
    words: [
      {jp:'昨日',r:'kinou',m:'Kecha'},{jp:'、',r:'',m:''},{jp:'家族',r:'kazoku',m:'Oila'},
      {jp:'と',r:'to',m:'bilan'},{jp:'レストラン',r:'resutoran',m:'Restoran'},{jp:'に',r:'ni',m:'ga'},
      {jp:'行きました',r:'ikimashita',m:'bordik'},{jp:'。',r:'',m:''},{jp:'ラーメン',r:'raamen',m:'Ramen'},
      {jp:'を',r:'wo',m:''},{jp:'注文',r:'chuumon',m:'Buyurtma'},{jp:'して',r:'shite',m:'bergancha'},
      {jp:'、',r:'',m:''},{jp:'みんなで',r:'minna de',m:'hammamiz'},{jp:'食べました',r:'tabemashita',m:'yedik'},
      {jp:'。',r:'',m:''},{jp:'とても',r:'totemo',m:'Juda'},{jp:'おいしかった',r:'oishikatta',m:'mazali edi'},
      {jp:'です',r:'desu',m:''},{jp:'。',r:'',m:''},
    ],
    translation: 'Kecha oila bilan restoranga bordik. Ramen buyurtma qilib, hammamiz yedik. Juda mazali edi.'
  },
];
